name: textstyle_extensions
description: Syntactic sugar for easily modifying TextStyles. Quickly create textStyle variants like .bold, .italic or .size().
version: 1.1.0
homepage: https://github.com/gskinnerTeam/flutter-textstyle-extensions

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
